Use MTF for tests
hpi-swa-teaching/SketchMorph2 pull request #46
Opened 2021-05-08 17:43 UTC by ClFeSc

Closes #45

2021-05-08 18:21 UTC, ClFeSc commented
My plan is to first move all tests to the new class. I already marked some tests as questionable, feel free to point out more such tests.

2021-05-09 09:21 UTC, maximilian-franz reviewed
Some files have two dots before the file ending, e.g. [baseline..st](packages/BaselineOfSketchMorph2.package/BaselineOfSketchMorph2.class/instance/baseline..st). Also, should we insert a newline at the end of a .st file (as suggested by github)?

Other than that, everything looks fine.

2021-05-09 09:21 UTC, maximilian-franz commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testHasColorPaletteEnoughColors.st
> +	palette := self subject colorPalette.
In my opinion the test is not necessary anymore.

2021-05-09 09:21 UTC, maximilian-franz commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testHasColorPaletteNoDuplicates.st
> +"Do we want to keep this test?"
In my opinion the test is not necessary anymore.

2021-05-09 12:28 UTC, ClFeSc commented
@maximilian-franz 
> Some files have two dots before the file ending, e.g. [baseline..st](https://github.com/hpi-swa-teaching/SketchMorph2/blob/1dd43fe91ab19732a304746d445927fff335bd99/packages/BaselineOfSketchMorph2.package/BaselineOfSketchMorph2.class/instance/baseline..st). 

Sure. What's the problem with them?
> Also, should we insert a newline at the end of a .st file (as suggested by github)?

I agree. I will add them to all files of the `MorphicMonetTests` class, the other files are out of scope of this PR, I think.

2021-05-09 13:13 UTC, maximilian-franz commented
@ClFeSc 

> Sure. What's the problem with them?

It's not necessarily a problem, it just looks a bit weird (at least to me).

2021-05-09 18:47 UTC, ClFeSc commented
@maximilian-franz 
> It's not necessarily a problem, it just looks a bit weird (at least to me).

I'm not sure if you know this, but Squeak uses `.` in file names wherever a `:` in the method signature is. So the file for the method `baseline:` will get the name `baseline.`, which is then appended to `.st`, thus creating `baseline..st`. I don't think there is much we can do about it.

2021-05-09 20:14 UTC, maximilian-franz commented
@ClFeSc 
> I'm not sure if you know this, but Squeak uses `.` in file names wherever a `:` in the method signature is. So the file for the method `baseline:` will get the name `baseline.`, which is then appended to `.st`, thus creating `baseline..st`. I don't think there is much we can do about it.

Ah ok, I didn't know that.

2021-05-10 15:58 UTC, DevSchmidtchen requested changes

2021-05-10 15:58 UTC, DevSchmidtchen commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/isButtonThere..st
> +	^ ((self lookForMenuWithItem: aLabel) isNil) not
`isNil not` should be equals to `notNil` and could be replaced.

2021-05-11 17:21 UTC, ScrappyDieRaupe commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testHasColorPaletteEvenAmountOfColors.st
> +"Do we want to keep this test?"
This one can be removed as well.

2021-05-15 13:43 UTC, johannes-poetzsch commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/doButtonAction..st
> +		aMorph doButtonAction]
missing newline

2021-05-15 13:44 UTC, maximilian-franz requested changes

2021-05-15 13:44 UTC, maximilian-franz commented on packages/SketchMorph2-Tests.package/MTFMorphWrapper.extension/instance/sendKey.modifiedBy..st
> +	self sendKeyEvent: #keystroke characterValue: aCharacter asInteger modifiedBy: aModifier.
Final newline is missing.

2021-05-15 13:44 UTC, maximilian-franz commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/doButtonAction..st
> +		aMorph doButtonAction]
Final newline is missing.

2021-05-15 13:48 UTC, maximilian-franz commented on packages/SketchMorph2-Tests.package/MTFMorphWrapper.extension/instance/sendKey.modifiedBy..st
> +	self sendKeyEvent: #keystroke characterValue: aCharacter asInteger modifiedBy: aModifier.
Also final dot

2021-05-15 13:55 UTC, johannes-poetzsch commented on packages/SketchMorph2-Tests.package/MTFMorphWrapper.extension/instance/sendKey.modifiedBy..st
> +	self sendKeyEvent: #keystroke characterValue: aCharacter asInteger modifiedBy: aModifier.
missing newLine

2021-05-15 13:55 UTC, johannes-poetzsch commented on packages/SketchMorph2-Tests.package/MTFMorphWrapper.extension/instance/sendKeyEvent.characterValue.modifiedBy..st
> +		self wait].
final dot should be removed

2021-05-15 13:55 UTC, johannes-poetzsch commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testPasteClipboardImage.st
> +
there seems to be an additional new line at the end that should be removed

2021-05-15 14:00 UTC, maximilian-franz approved these changes

2021-05-15 14:49 UTC, ScrappyDieRaupe approved these changes

2021-05-16 12:15 UTC, johannes-poetzsch approved these changes

2021-05-16 12:54 UTC, jannis-hpi approved these changes

2021-05-16 16:13 UTC, DevSchmidtchen approved these changes

2021-05-16 16:17 UTC, merged