Allow variable canvas size
hpi-swa-teaching/SketchMorph2 pull request #48
Opened 2021-05-16 18:12 UTC by ClFeSc

Closes #36

2021-05-17 07:12 UTC, DevSchmidtchen commented
Clicking undo doesn't update the position of the GripMorph.

2021-05-18 10:29 UTC, maximilian-franz requested changes
The M2GripMorph class is missing a class comment.

2021-05-18 10:29 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2Canvas.class/instance/fastFramingOn.st
> +	^ true
Final newline missing.

2021-05-18 10:29 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2GripMorph.class/instance/initialize.st
> +	self updatePosition
A cascade would be appropriate here.

2021-05-18 10:29 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2GripMorph.class/instance/target.st
> +	^ target
Final newline missing.

2021-05-18 10:29 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/MorphicMonet.class/instance/importPNG..st
> +	self canvas updateGripMorphPosition
A cascade would be appropriate here.

2021-05-18 10:29 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/MorphicMonet.class/instance/loadCanvas.st
> +	self canvas addGripMorph: (M2GripMorph newOn: self canvas)
A cascade would be appropriate here.

2021-05-18 10:29 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/MorphicMonet.class/instance/undo.st
> +	self canvas updateGripMorphPosition
A cascade would be appropriate here.

2021-05-18 10:30 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2Canvas.class/instance/fastFramingOn.st
> +	^ true
Also, there's a newline after the method name

2021-05-18 13:28 UTC, DevSchmidtchen requested changes

2021-05-18 13:28 UTC, DevSchmidtchen commented on packages/SketchMorph2-Core.package/M2Canvas.class/instance/addGripMorph..st
> +	self gripMorph: aM2GripMorph
Cascade

2021-05-18 19:03 UTC, johannes-poetzsch commented on packages/SketchMorph2-Core.package/M2GripMorph.class/class/newOn..st
> +as yet unclassified
the method category seems to be missing

2021-05-18 19:05 UTC, johannes-poetzsch approved these changes

2021-05-18 19:10 UTC, johannes-poetzsch requested changes
there is an unclassified method

2021-05-18 19:10 UTC, johannes-poetzsch commented on packages/SketchMorph2-Core.package/M2GripMorph.class/class/newOn..st
> +as yet unclassified
missing classification

2021-05-18 23:10 UTC, ScrappyDieRaupe approved these changes

2021-05-19 10:03 UTC, ClFeSc commented
I can only draw on the original canvas size, regardless of the visible size.

2021-05-19 10:14 UTC, ClFeSc reviewed
Code-wise this looks very good. Just replace the green box with something fancy and fix [this](https://github.com/hpi-swa-teaching/SketchMorph2/pull/48#issuecomment-843949753) bug.

2021-05-19 10:14 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Canvas.class/instance/initialize.st
> +		yourself
Why `yourself`? We are not returning this.

2021-05-19 10:14 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2GripMorph.class/class/newOn..st
> +as yet unclassified
Method is not classified.

2021-05-19 10:14 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2GripMorph.class/instance/initialize.st
> +		color: Color green;
Needs to be updated before merging.

2021-05-19 10:14 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2GripMorph.class/instance/updatePosition.st
> +initialization
Since `updatePosition` gets called during the lifetime of the object, I think this category no longer applies.

2021-05-19 10:14 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2GripMorph.class/properties.json
> +		"cursorOffset" ],
These should be ordered alphabetically.

2021-05-19 13:52 UTC, ScrappyDieRaupe approved these changes

2021-05-19 13:56 UTC, johannes-poetzsch approved these changes

2021-05-19 17:34 UTC, ClFeSc commented
> I can only draw on the original canvas size, regardless of the visible size.

Fixed with [d46fb9f](https://github.com/hpi-swa-teaching/SketchMorph2/pull/48/commits/d46fb9f7124ecabf37ef0a99f6eebce33f08947d).

2021-05-19 17:54 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2GripMorph.class/instance/initialize.st
> +		color: Color green;
Adjusted in [1802a96](https://github.com/hpi-swa-teaching/SketchMorph2/pull/48/commits/1802a96f3eb74a27efb63c387e2fb00b2f692b1d).

2021-05-19 18:04 UTC, ClFeSc commented
As the tests currently don't contain a canvas at all, for now, we don't write any tests for the grip morph. When @maximilian-franz and @DevSchmidtchen approve this PR, it can be merged.

2021-05-19 18:09 UTC, maximilian-franz approved these changes

2021-05-19 18:30 UTC, merged