Ignore Ctrl+V for image import while editing text
hpi-swa-teaching/SketchMorph2 pull request #75
Opened 2021-06-10 07:39 UTC by ClFeSc

Closes #74

2021-06-16 11:45 UTC, jannis-hpi approved these changes

2021-06-16 13:02 UTC, ScrappyDieRaupe approved these changes

2021-06-16 13:13 UTC, DevSchmidtchen approved these changes

2021-06-26 17:25 UTC, maximilian-franz approved these changes

2021-06-26 20:07 UTC, johannes-poetzsch approved these changes

2021-06-28 10:35 UTC, ScrappyDieRaupe requested changes
Lorem ipsum

2021-06-28 16:52 UTC, merged