Tool Preview
hpi-swa-teaching/SketchMorph2 pull request #79
Opened 2021-06-16 13:30 UTC by DevSchmidtchen

Closes #55

2021-06-26 10:20 UTC, ClFeSc requested changes

2021-06-26 10:20 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/chooseFont.st
> +	self currentCursor: nil.
This probably leads to the problem that, after choosing the font, no context cursor is shown.

2021-06-26 10:20 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/clearCanvas.st
> +		currentCursor: nil.
This probably leads to no context cursor being shown after clearing the canvas.

2021-06-26 10:20 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/drawEraser.st
> +		currentCursor: (Form dotOfSize: self eraserSize color: Color white);
I don't really like the concept of a white cursor on a mostly white background. When there is not much color on the canvas, one can barely find the cursor.

2021-06-26 10:20 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/drawTriangle.st
> +		switchMode
Missing newline.

2021-06-26 10:20 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/fillShape.st
> +		currentCursor: M2FillArea icon;
This cursor is not transparent.

2021-06-26 10:20 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Canvas.class/instance/mouseLeave..st
> +
One line too much.

2021-06-26 10:20 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2IconMenuItem.class/class/cursor.st
> +	^ self subclassResponsibility
This subclass responsibility seems to be not implemented.

2021-06-26 17:01 UTC, ClFeSc approved these changes

2021-06-26 17:22 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/drawCircle.st
> +		currentCursor: (Form dotOfSize: self brushSize color: self penColor);
Maybe we should add a cursor for that like we did for `drawEraser` to make the code more consistent.

2021-06-26 17:22 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/drawRectangle.st
> +		currentCursor: ((Form extent: self rectangleBrushSize depth: self defaultDepth)
Maybe we should add a cursor for that like we did for `drawEraser` to make the code more consistent.

2021-06-26 17:22 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2Backend.class/instance/drawTriangle.st
> +		currentCursor: ((Form extent: self brushSize asPoint depth: self defaultDepth) fillShape: self prepareTrianglePenSource fillColor: self currentColor);
Maybe we should add a cursor for that like we did for `drawEraser` to make the code more consistent.

2021-06-27 10:22 UTC, ScrappyDieRaupe approved these changes

2021-06-27 18:00 UTC, maximilian-franz approved these changes

2021-06-28 16:19 UTC, jannis-hpi approved these changes

2021-06-28 16:55 UTC, johannes-poetzsch approved these changes

2021-06-28 20:01 UTC, merged