JPEG Import II
hpi-swa-teaching/SketchMorph2 pull request #89
Opened 2021-06-29 09:44 UTC by ClFeSc

Closes #71 

Follow-up from #78

2021-06-29 09:49 UTC, maximilian-franz requested changes

2021-06-29 09:49 UTC, maximilian-franz commented on packages/SketchMorph2-Tests.package/M2DrawingComponentTests.class/instance/testCachedFormAfterImport.st
>  	self compare: self backend cachedForm with: #importTestPNG
Missing newline.

2021-06-29 09:49 UTC, maximilian-franz commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testDoesImportImageSendCorrectMessage.st
> +	self assert: self subject backend lastCalledMethod == #importImage:
```suggestion
	self
		doButtonAction: 'Import Image';
		assert: self subject backend lastCalledMethod == #importImage:
```

2021-06-29 15:34 UTC, DevSchmidtchen approved these changes

2021-06-29 16:48 UTC, maximilian-franz approved these changes

2021-06-30 10:24 UTC, ScrappyDieRaupe approved these changes

2021-06-30 10:28 UTC, johannes-poetzsch approved these changes

2021-06-30 14:53 UTC, jannis-hpi approved these changes

2021-06-30 15:02 UTC, merged