make text movable
hpi-swa-teaching/SketchMorph2 pull request #94
Opened 2021-07-08 17:01 UTC by johannes-poetzsch

Closes #70

2021-07-11 18:29 UTC, ScrappyDieRaupe requested changes
There is a missing newline in almost every new method and missing spaces around '@'. I believe you left them on purpose in order to test the auto-refactoring?
A class comment should be added anyway.

2021-07-11 18:32 UTC, ClFeSc commented
> There is a missing newline in almost every new method and missing spaces around '@'. I believe you left them on purpose in order to test the auto-refactoring?
> A class comment should be added anyway.

I can confirm that I, while doing this with @johannes-poetzsch, did not care about those because I knew we had the auto-refactor.

But you are right that there are some things we did not do yet, one of which is the class comment.

2021-07-11 22:49 UTC, johannes-poetzsch commented on packages/SketchMorph2-Core.package/M2TemporaryTextMorph.class/instance/defaultHandleOffset.st
> +	^ self topCenter - (10@20)
This should depend on the handle's extend

2021-07-12 10:30 UTC, maximilian-franz reviewed
Will approve after auto refactoring and addition of class comment.

2021-07-12 10:30 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2TemporaryTextMorph.class/instance/moveByHandleTo..st
> +as yet unclassified
Should be classified

2021-07-14 07:41 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2TemporaryTextMorph.class/instance/defaultHandleOffset.st
> +	^ self topCenter - (self defaultHandleExtent * (0.5@1))
I think putting the handle at the bottom right corner (like we do with the canvas grip morph) would be better, but that's just personal preference. Maybe the customer has an opinion on that?

2021-07-14 12:58 UTC, ScrappyDieRaupe commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testDoesTextHandleMoveText.st
> +	self assert: targetPosition + ((0@0.5) * handle extent) equals: temporaryTextMorph topCenter
👍

2021-07-14 13:03 UTC, ScrappyDieRaupe commented on packages/SketchMorph2-Tests.package/M2DrawingComponentTests.class/instance/testSimpleTextAfterMovingByHandle.st
> +	self viewPort temporaryTextMorph position: self viewPort temporaryTextMorph topCenter.
You are setting the position by moving the handle in the first line and overwriting it in the second, if I understand correctly. Doesn't it render the first line useless?

2021-07-14 13:58 UTC, DevSchmidtchen approved these changes

2021-07-14 13:58 UTC, ScrappyDieRaupe approved these changes

2021-08-02 15:14 UTC, maximilian-franz approved these changes

2021-08-02 15:19 UTC, ClFeSc requested changes

2021-08-02 15:19 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/M2DrawingComponentTests.class/instance/testSimpleTextAfterMovingByHandle.st
> +	self viewPort temporaryTextMorph position: self viewPort temporaryTextMorph bottomRight.
This could be converted to a cascade.

2021-08-02 15:19 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/M2DrawingComponentTests.class/instance/testSimpleTextAfterMovingOutside.st
> +	self viewPort temporaryTextMorph moveByHandleTo: 200 asPoint.
Maybe also a cascade.

2021-08-02 15:19 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testDoesTextHandleMoveText.st
> +	event := self subject generateMouseEvent: #mouseMove button: MTFMorphWrapper leftButton on: handle.
We should check whether this line is required.

2021-08-02 15:19 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testIsTemporaryTextMorphThere.st
> +
One line too much.

2021-08-02 15:19 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testIsTemporaryTextMorphThere.st
> +	collection := self subject canvas submorphsSatisfying: [:morph | morph class = M2TemporaryTextMorph].
Is `morph class = M2TemporaryTextMorph` ok to use? Or should we use something like `isM2TemporaryTextMorph`?

2021-08-02 15:19 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testIsTemporaryTextMorphThere.st
> +	self assert: self subject canvas center equals: ((collection at: 1) position)
Maybe `first` instead of `at: 1`?

2021-08-02 15:19 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testIsTextHandleThere.st
> +	self assert: self subject canvas equals: (handle ownerChain at: 3).
I'm not sure `handle ownerChain at: 3` is ideal. Also unnecessary brackets.

2021-08-02 15:21 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testDoesTextHandleMoveText.st
> +	event := self subject generateMouseEvent: #mouseMove button: MTFMorphWrapper leftButton on: handle.
Ok, I didn't notice the upper one is `#mouseDown` and this is `#mouseMove`.

2021-08-02 15:28 UTC, ClFeSc approved these changes
Apart from the comments I added with my old review, which I don't think should block us too much, this looks fine to me.

2021-08-02 20:01 UTC, maximilian-franz approved these changes

2021-08-04 13:34 UTC, merged