Add selection tool
hpi-swa-teaching/SketchMorph2 pull request #95
Opened 2021-07-08 17:13 UTC by DevSchmidtchen

Closes #33

2021-07-09 12:29 UTC, DevSchmidtchen commented
ToDo:

- [ ] Deactivate Insert Button if nothing in clipboard
- [ ] Fix tests by using `MorphicMonetIcons` instead of `UiFugueIcons`
- [ ] Add tests

2021-07-12 09:12 UTC, ClFeSc requested changes

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2DrawingComponent.class/instance/clickAt..st
> +	self context isInInsertSelectionMode ifTrue: [self projectSelectionAt: aPoint. ^ self]
While we're at it we can further simplify this by returning the method called in each block since they all return `self`:
```suggestion
	self context isInFillMode ifTrue: [^ self fillShapeAt: aPoint].
	(self context isInPenMode or: [self context isInGeometricPreviewMode]) 
		ifTrue: [^ self startDrawingAt: aPoint].
	self context isInTextMode ifTrue: [^ self startEditingTextAt: aPoint].
	self context isInEditingTextMode ifTrue: [^ self printText].
	self context isInInsertSelectionMode ifTrue: [^ self projectSelectionAt: aPoint]
```

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2DrawingComponent.class/instance/insertSelection.st
> +
Why is this defined in the Component? Does the Backend ever use it?

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2DrawingComponent.class/instance/startSelection.st
> +	self switchMode
Same question: Is this ever called by the Backend?

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2DrawingContext.class/properties.json
> +		"currentGeometricPreviewShape" ],
Should be sorted alphabetically.

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Select.class/properties.json
> +{
Class is missing class comment.

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2Select.class/class/label.st
> +	^ 'Select'
Maybe something like `Select Area` would better represent the functionality of the button,

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2ViewPort.class/instance/insertSelection.st
> +			offset: (self brushSize asPoint / 2 + (self clipboardForm extent * self scalar * 0.5) negated));
Does `negated` apply to the whole calculation or just the last part after the `+`?

2021-07-12 09:12 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2ViewPort.class/properties.json
> +		"clipboardForm" ],
Should be alphabetically sorted.

2021-07-14 16:13 UTC, DevSchmidtchen commented on packages/SketchMorph2-Core.package/M2DrawingComponent.class/instance/insertSelection.st
> +
We tried to implement it only in the `M2ViewPort`, but then `reloadCurrentPen` on `M2Backend` failed.

2021-08-02 15:57 UTC, ClFeSc requested changes

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2ViewPort.class/instance/insertSelection.st
> +			offset: (self brushSize asPoint / 2 - (self clipboardForm extent * self scalar * 0.5)));
I think we should try to at least in one line use `/ 2` or `* 0.5` consistently.

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/M2DrawingComponentTests.class/instance/testCompareClipboardInsertion.st
> +
One line too much.

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/M2DrawingComponentTests.class/instance/testCompareSelection.st
> +		drawFrom: (40 @ 40) To: (60 @ 60);
```suggestion
		drawFrom: 40 asPoint To: 60 asPoint;
```

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/getButtonFor..st
> +    self assert: buttons morphs size equals: 1.
```suggestion
    self assert: 1 equals: buttons morphs size.
```
The value after `assert:` is the expected one, the other is the actual one.

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/getButtonFor..st
> +	^ buttons morphs asOrderedCollection first
```suggestion
	^ buttons morphs anyOne
```
This would skip the creation of a new `OrderedCollection`.

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/getButtonFor..st
> +        (aMorph respondsTo: #contents) and: [aMorph contents = aLabel]].
We can remove the first condition once #93 is merged.

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/MorphicMonet.class/instance/findMenuItemWith..st
> +			item isMenuItemMorph and: [item contents = aString]] ifFound: [:item | ^ item]].
We can remove the first condition once #93 is merged.

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testIsInsertSelectionButtonThere.st
> +testIsInsertSelectionButtonThere
It doesn't seem like the test is testing what the name implies.

2021-08-02 15:57 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testIsInsertSelectionButtonThere.st
> +	self assert: (self isButtonEnabled: buttonLabel) not
```suggestion
	self deny: self isButtonEnabled: buttonLabel
```

2021-08-04 12:44 UTC, ScrappyDieRaupe approved these changes

2021-08-04 12:49 UTC, maximilian-franz approved these changes

2021-08-04 12:50 UTC, ClFeSc approved these changes

2021-08-04 12:54 UTC, johannes-poetzsch approved these changes

2021-08-04 13:00 UTC, merged