Feature/92 brush size indicator
hpi-swa-teaching/SketchMorph2 pull request #98
Opened 2021-07-14 13:08 UTC by ScrappyDieRaupe

Closes #92

2021-07-26 13:13 UTC, maximilian-franz requested changes
`M2BrushSizeIndicator` is missing a class comment.

2021-07-26 13:13 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2BrushSizeIndicator.class/instance/model.st
> +	^ model
final newline

2021-07-26 13:13 UTC, maximilian-franz commented on packages/SketchMorph2-Core.package/M2BrushSizeIndicator.class/instance/model..st
> +	model := anObject
`anObject` should be `anM2DrawingComponent`, also final newline

2021-07-31 20:32 UTC, ScrappyDieRaupe commented on packages/SketchMorph2-Core.package/MorphicMonet.class/instance/initializeColorPanel.st
> +			extent: self defaultColorPanelExtent;
'Extract method' might be appropriate here. 
Apart from that, everything else looks well done.

2021-08-01 16:30 UTC, ClFeSc requested changes

2021-08-01 16:30 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/MorphicMonet.class/instance/defaultColorPanelExtent.st
> +	^ 325 @ 250
On my system this is too small, leading to the color panel moving when the brush size is big. We've fixed this on `current-alpha` by doing:
```suggestion
	^ 350 @ 250
```
I'm not sure this will solve this problem for all systems, though.

2021-08-01 16:30 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/MorphicMonet.class/instance/defaultBrushSizeIndicator.st
> +	^ (M2BrushSizeIndicator newOn: self backend) name: #brushSizeIndicator
Isn't the name already set in the initialization of the indicator?

2021-08-01 16:30 UTC, ClFeSc commented on packages/SketchMorph2-Core.package/M2BrushSliderMorph.class/instance/initialize.st
> +		maxVal: 75;
Why are we reducing the maximum brush size?

2021-08-01 16:30 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testDoesBrushSizeIndicatorAdjustToBrushSize.st
> +	self assert: (indicator extent = 30 asPoint)
```suggestion
	self assert: 30 asPoint equals: indicator extent
```

2021-08-01 16:30 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testIsBrushSizeIndicatorThere.st
> +	self assert: (indicatorWrapper morphs notEmpty)
Maybe consider checking whether there is exactly one element?

2021-08-01 16:30 UTC, ClFeSc commented on packages/SketchMorph2-Tests.package/MorphicMonetTests.class/instance/testDoesBrushSizeIndicatorAdjustToBrushSize.st
> +	indicator := indicatorWrapper morphs asOrderedCollection first.
```suggestion
	indicator := indicatorWrapper morphs anyOne.
```
This would eliminate the need of converting the collection.

2021-08-01 16:57 UTC, johannes-poetzsch commented on packages/SketchMorph2-Core.package/M2BrushSliderMorph.class/instance/initialize.st
> +		maxVal: 75;
Because the customer said so.

2021-08-01 17:10 UTC, ClFeSc approved these changes

2021-08-04 12:52 UTC, maximilian-franz approved these changes

2021-08-04 12:56 UTC, DevSchmidtchen approved these changes

2021-08-04 12:57 UTC, johannes-poetzsch approved these changes

2021-08-04 13:28 UTC, merged